modLoader="javafml"
loaderVersion="[37,)"
license="Apache License 2.0"

[[mods]] 
	modId="serverpassword" 
	version="${version}" 
	displayName="ServerPassword"
	description='''Securely login to a minecraft server using your password!'''
	side="SERVER"
	authors="PT400C - Jomcraft Network"
	credits="Developed by Jomcraft Network 2021"

[[dependencies.serverpassword]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.serverpassword]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,]"
    ordering="NONE"
    side="BOTH"